version: 2

build:
  os: ubuntu-22.04
  tools:
    python: latest
  pre_create_environment:
    - pip install hatch
    - hatch --env docs dep show requirements > requirements.txt

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
