from enum import Enum

class RTAMTException(Exception): ...
class LTLException(RTAMTException): ...
class LTLPastifyException(LTLException): ...
class LTLParseException(LTLException): ...
class LTLOfflineException(LTLException): ...
class LTLSpecificationException(LTLException): ...
class LTLNotImplementedException(LTLException): ...
class STLException(RTAMTException): ...
class STLParseException(STLException): ...
class STLOfflineException(STLException): ...
class STLSpecificationException(STLException): ...
class STLNotImplementedException(STLException): ...

class Semantics(Enum):
    STANDARD = ...
    OUTPUT_ROBUSTNESS = ...
    INPUT_VACUITY = ...
    INPUT_ROBUSTNESS = ...
    OUTPUT_VACUITY = ...

class Language(Enum):
    PYTHON = ...
    CPP = ...

class _BaseSpecification:
    spec: str
    def __init__(self) -> None: ...
    def declare_var(self, name: str, type: str) -> None: ...
    def parse(self) -> None: ...
    def pastify(self) -> None: ...
    def reset(self) -> None: ...

class StlDenseTimeSpecification(_BaseSpecification):
    def evaluate(
        self, *args: tuple[str, list[tuple[float, float]]]
    ) -> list[tuple[float, float]]: ...

class StlDiscreteTimeSpecification(_BaseSpecification):
    def set_sampling_period(self, period: float, unit: str, tolerance: float) -> None: ...
    def evaluate(self, data: dict[str, list[float]]) -> list[tuple[float, float]]: ...
