from typing import Union

from numpy import float_, int_
from numpy.typing import NDArray

def figure(num: int) -> None: ...
def subplot(total: int, x: int, y: int) -> None: ...
def plot(x_axis: NDArray[Union[float_, int_]], y_axis: NDArray[Union[float_, int_]]) -> None: ...
def show() -> None: ...
