from ..exception import RTAMTException

class LTLException(RTAMTException): ...
class LTLPastifyException(LTLException): ...
class LTLParseException(LTLException): ...
class LTLOfflineException(LTLException): ...
class LTLSpecificationException(LTLException): ...
class LTLNotImplementedException(LTLException): ...
