from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Generic, TypeVar

from ..cost_func import Result
from ..models import Trace

S = TypeVar("S", contravariant=True)
C = TypeVar("C", covariant=True)
E = TypeVar("E", covariant=True)
R = TypeVar("R", covariant=True)


class Specification(ABC, Generic[S, C, E]):
    """Class that represents a requirement to be evaluated using simulation data.

    A specification should accept the trajectories and timestamps generated by a model and return
    a value which represents the "goodness" of the model results with respect to some criteria.
    """

    @abstractmethod
    def evaluate(self, __trace: Trace[S]) -> Result[C, E]:
        """Evaluate trajectories and timestamps with respect to some requirement.

        Args:
            trajectories: Matrix of states where each row represents a state variable.
            timestamps: Vector of time values corresponding to each column of the trajectories
                        matrix.

        Returns:
            A value indicating the "goodness" of the trajectories according to the requirement.
        """

        ...
