from __future__ import annotations

from enum import Enum

class Semantics(Enum):
    STANDARD = ...
    OUTPUT_ROBUSTNESS = ...
    INPUT_VACUITY = ...
    INPUT_ROBUSTNESS = ...
    OUTPUT_VACUITY = ...
