name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

env:
  UV_NO_DEV: True # Disable dev dependency group in all jobs

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: uv run --group tests pytest

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.12"
      - name: Run Tests
        run: uv run --group docs sphinx-build -b html docs docs/_build/html

  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup environment
        run: uv sync --group examples
      - name: Run F16
        run: uv run examples/f16.py
      - name: Run Nonlinear
        run: uv run examples/nonlinear.py
