from ..exception import RTAMTException

class STLException(RTAMTException): ...
class STLParseException(STLException): ...
class STLOfflineException(STLException): ...
class STLSpecificationException(STLException): ...
class STLNotImplementedException(STLException): ...
